#!/bin/sh
# Ensure LuCI ucitrack restarts frps on Save & Apply

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frps[-1]
	add ucitrack frps
	set ucitrack.@frps[-1].init='frps'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null || true
exit 0
